import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | ScoreMyCV",
  description: "Terms and Conditions and Privacy Policy for ScoreMyCV.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white px-4 py-16 sm:px-6">
      <div className="max-w-3xl mx-auto">

        <div className="mb-10">
          <a href="/" className="text-blue-600 text-sm font-medium hover:underline">← Back to ScoreMyCV</a>
        </div>

        <h1 className="text-3xl font-extrabold text-slate-900 mb-2">Terms &amp; Conditions and Privacy Policy</h1>
        <p className="text-slate-400 text-sm mb-10">ScoreMyCV · scoremycv.in · Last updated: September 2026</p>

        <div className="space-y-10 text-slate-700 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">1. About Us</h2>
            <p>ScoreMyCV (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is operated as a sole proprietorship. We provide ATS resume scoring and CV rewriting services through our website scoremycv.in.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">2. Acceptance of Terms</h2>
            <p>By using our website and services, you confirm that you have read, understood, and agree to these Terms &amp; Conditions. If you do not agree, please do not use our services.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">3. Services</h2>
            <p>We offer:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>Free ATS score check for uploaded CVs</li>
              <li>Paid CV rewriting service</li>
              <li>PDF download of rewritten CV</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">4. Data We Collect</h2>
            <p>We collect:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>Your CV/resume (uploaded by you)</li>
              <li>Name, email address, phone number, and location (extracted from your CV)</li>
              <li>Job role preference</li>
              <li>Payment details (processed securely by Razorpay — we do not store card details)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">5. How We Use Your Data</h2>
            <p>Your data is used to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>Provide ATS scoring and CV rewriting services</li>
              <li>Improve our service quality</li>
              <li>Share with our partner companies for relevant job, course, and career opportunities (only where you have agreed to our T&amp;C)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">6. Data Storage</h2>
            <p>Your CV and extracted information are stored securely on our servers. By using our service, you consent to this storage.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">7. Third-Party Sharing</h2>
            <p>By agreeing to these Terms, you acknowledge that your contact information (name, email, phone) may be shared with carefully selected partner companies offering career-related products and services such as job opportunities, upskilling courses, and recruitment services.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">8. Payments &amp; Refunds</h2>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>Payments are processed securely via Razorpay</li>
              <li>Our current pricing is displayed on the website at the time of purchase</li>
              <li>Refunds are considered on a case-by-case basis. Contact us at <a href="mailto:scoremycv.in@gmail.com" className="text-blue-600 underline">scoremycv.in@gmail.com</a> within 24 hours of purchase</li>
              <li>No refund will be issued once the rewritten CV has been downloaded</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">9. Intellectual Property</h2>
            <p>The rewritten CV generated by our service is provided for your personal use. You may not resell or redistribute it.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">10. Limitation of Liability</h2>
            <p>ScoreMyCV provides its services on a best-effort basis. We do not guarantee job interviews or employment outcomes. Our maximum liability is limited to the amount paid by you for the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">11. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in India.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">12. Grievance Officer</h2>
            <p>As required under applicable Indian law, you may contact our Grievance Officer for any data-related concerns:</p>
            <p className="mt-2">Email: <a href="mailto:scoremycv.in@gmail.com" className="text-blue-600 underline">scoremycv.in@gmail.com</a></p>
            <p>Response time: within 30 days</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-2">13. Changes to Terms</h2>
            <p>We reserve the right to update these Terms at any time. Continued use of the service after changes constitutes acceptance.</p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-slate-100 text-center text-slate-400 text-xs">
          © {new Date().getFullYear()} ScoreMyCV · <a href="mailto:scoremycv.in@gmail.com" className="hover:text-blue-600">scoremycv.in@gmail.com</a>
        </div>

      </div>
    </main>
  );
}
